# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcayleyCpp <- function(n, kappa) {
    .Call('_rotations_rcayleyCpp', PACKAGE = 'rotations', n, kappa)
}

rmbCpp <- function(n, kappa) {
    .Call('_rotations_rmbCpp', PACKAGE = 'rotations', n, kappa)
}

rfisherCpp <- function(n, kappa) {
    .Call('_rotations_rfisherCpp', PACKAGE = 'rotations', n, kappa)
}

rvmisesCPP <- function(n, kappa) {
    .Call('_rotations_rvmisesCPP', PACKAGE = 'rotations', n, kappa)
}

centerCpp <- function(Rs, S) {
    .Call('_rotations_centerCpp', PACKAGE = 'rotations', Rs, S)
}

lpvmises <- function(Rs, S, kappa) {
    .Call('_rotations_lpvmises', PACKAGE = 'rotations', Rs, S, kappa)
}

lpfisher <- function(Rs, S, kappa) {
    .Call('_rotations_lpfisher', PACKAGE = 'rotations', Rs, S, kappa)
}

lpcayley <- function(Rs, S, kappa) {
    .Call('_rotations_lpcayley', PACKAGE = 'rotations', Rs, S, kappa)
}

S_MCMC_CPP <- function(Rs, oldS, rho, kappa, Dist) {
    .Call('_rotations_S_MCMC_CPP', PACKAGE = 'rotations', Rs, oldS, rho, kappa, Dist)
}

kap_MCMC_CPP <- function(Rs, oldKappa, sigma, S, Dist) {
    .Call('_rotations_kap_MCMC_CPP', PACKAGE = 'rotations', Rs, oldKappa, sigma, S, Dist)
}

afun_CPP <- function(R1, R2) {
    .Call('_rotations_afun_CPP', PACKAGE = 'rotations', R1, R2)
}

both_MCMC_CPP <- function(Rs, S0, kappa0, rho, sigma, burnin, B, Dist) {
    .Call('_rotations_both_MCMC_CPP', PACKAGE = 'rotations', Rs, S0, kappa0, rho, sigma, burnin, B, Dist)
}

fisherAxisC <- function(Qs, Qhat) {
    .Call('_rotations_fisherAxisC', PACKAGE = 'rotations', Qs, Qhat)
}

fisherAxisCSymmetric <- function(Qs, Qhat) {
    .Call('_rotations_fisherAxisCSymmetric', PACKAGE = 'rotations', Qs, Qhat)
}

fisherBootC <- function(Qs, m, symm) {
    .Call('_rotations_fisherBootC', PACKAGE = 'rotations', Qs, m, symm)
}

RdistC <- function(Q1, Q2) {
    .Call('_rotations_RdistC', PACKAGE = 'rotations', Q1, Q2)
}

rdistSO3C <- function(Rs, R2) {
    .Call('_rotations_rdistSO3C', PACKAGE = 'rotations', Rs, R2)
}

EdistC <- function(Q1, Q2) {
    .Call('_rotations_EdistC', PACKAGE = 'rotations', Q1, Q2)
}

oneRdistC <- function(Q1, Q2) {
    .Call('_rotations_oneRdistC', PACKAGE = 'rotations', Q1, Q2)
}

cdfunsC <- function(Qs, Qhat) {
    .Call('_rotations_cdfunsC', PACKAGE = 'rotations', Qs, Qhat)
}

cdfunsCMedian <- function(Qs, Qhat) {
    .Call('_rotations_cdfunsCMedian', PACKAGE = 'rotations', Qs, Qhat)
}

zhangQ4 <- function(Q, m) {
    .Call('_rotations_zhangQ4', PACKAGE = 'rotations', Q, m)
}

cdfunsCSO3 <- function(Rs, Rhat) {
    .Call('_rotations_cdfunsCSO3', PACKAGE = 'rotations', Rs, Rhat)
}

zhangMedianC <- function(Rs, m) {
    .Call('_rotations_zhangMedianC', PACKAGE = 'rotations', Rs, m)
}

eskewC <- function(U) {
    .Call('_rotations_eskewC', PACKAGE = 'rotations', U)
}

SO3defaultC <- function(U, theta) {
    .Call('_rotations_SO3defaultC', PACKAGE = 'rotations', U, theta)
}

Q4defaultC <- function(U, theta) {
    .Call('_rotations_Q4defaultC', PACKAGE = 'rotations', U, theta)
}

pMatC <- function(p) {
    .Call('_rotations_pMatC', PACKAGE = 'rotations', p)
}

genrC <- function(r, S, SO3, u) {
    .Call('_rotations_genrC', PACKAGE = 'rotations', r, S, SO3, u)
}

checkQ4 <- function(Q) {
    .Call('_rotations_checkQ4', PACKAGE = 'rotations', Q)
}

checkSO3 <- function(Rs) {
    .Call('_rotations_checkSO3', PACKAGE = 'rotations', Rs)
}

expskewC <- function(M) {
    .Call('_rotations_expskewC', PACKAGE = 'rotations', M)
}

expskewCMulti <- function(M) {
    .Call('_rotations_expskewCMulti', PACKAGE = 'rotations', M)
}

logSO3C <- function(R) {
    .Call('_rotations_logSO3C', PACKAGE = 'rotations', R)
}

logSO3CMulti <- function(R) {
    .Call('_rotations_logSO3CMulti', PACKAGE = 'rotations', R)
}

projectSO3C <- function(M) {
    .Call('_rotations_projectSO3C', PACKAGE = 'rotations', M)
}

meanSO3C <- function(Rs) {
    .Call('_rotations_meanSO3C', PACKAGE = 'rotations', Rs)
}

meanQ4C <- function(Q) {
    .Call('_rotations_meanQ4C', PACKAGE = 'rotations', Q)
}

medianSO3C <- function(Rs, maxIterations, maxEps) {
    .Call('_rotations_medianSO3C', PACKAGE = 'rotations', Rs, maxIterations, maxEps)
}

HartmedianSO3C <- function(Rs, maxIterations, maxEps) {
    .Call('_rotations_HartmedianSO3C', PACKAGE = 'rotations', Rs, maxIterations, maxEps)
}

gmeanSO3C <- function(Rs, maxIterations, maxEps) {
    .Call('_rotations_gmeanSO3C', PACKAGE = 'rotations', Rs, maxIterations, maxEps)
}

HnCpp <- function(Qs) {
    .Call('_rotations_HnCpp', PACKAGE = 'rotations', Qs)
}

HnCppIntrinsic <- function(Qs) {
    .Call('_rotations_HnCppIntrinsic', PACKAGE = 'rotations', Qs)
}

HnCppBloc <- function(Qs, Cs) {
    .Call('_rotations_HnCppBloc', PACKAGE = 'rotations', Qs, Cs)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_rotations_RcppExport_registerCCallable', PACKAGE = 'rotations')
})
