# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eskewC <- function(U) {
    .Call('rotations_eskewC', PACKAGE = 'rotations', U)
}

SO3defaultC <- function(U, theta) {
    .Call('rotations_SO3defaultC', PACKAGE = 'rotations', U, theta)
}

Q4defaultC <- function(U, theta) {
    .Call('rotations_Q4defaultC', PACKAGE = 'rotations', U, theta)
}

pMatC <- function(p) {
    .Call('rotations_pMatC', PACKAGE = 'rotations', p)
}

genrC <- function(r, S, SO3, u) {
    .Call('rotations_genrC', PACKAGE = 'rotations', r, S, SO3, u)
}

checkQ4 <- function(Q) {
    .Call('rotations_checkQ4', PACKAGE = 'rotations', Q)
}

checkSO3 <- function(Rs) {
    .Call('rotations_checkSO3', PACKAGE = 'rotations', Rs)
}

expskewC <- function(M) {
    .Call('rotations_expskewC', PACKAGE = 'rotations', M)
}

expskewCMulti <- function(M) {
    .Call('rotations_expskewCMulti', PACKAGE = 'rotations', M)
}

logSO3C <- function(R) {
    .Call('rotations_logSO3C', PACKAGE = 'rotations', R)
}

logSO3CMulti <- function(R) {
    .Call('rotations_logSO3CMulti', PACKAGE = 'rotations', R)
}

projectSO3C <- function(M) {
    .Call('rotations_projectSO3C', PACKAGE = 'rotations', M)
}

meanSO3C <- function(Rs) {
    .Call('rotations_meanSO3C', PACKAGE = 'rotations', Rs)
}

meanQ4C <- function(Q) {
    .Call('rotations_meanQ4C', PACKAGE = 'rotations', Q)
}

medianSO3C <- function(Rs, maxIterations, maxEps) {
    .Call('rotations_medianSO3C', PACKAGE = 'rotations', Rs, maxIterations, maxEps)
}

HartmedianSO3C <- function(Rs, maxIterations, maxEps) {
    .Call('rotations_HartmedianSO3C', PACKAGE = 'rotations', Rs, maxIterations, maxEps)
}

gmeanSO3C <- function(Rs, maxIterations, maxEps) {
    .Call('rotations_gmeanSO3C', PACKAGE = 'rotations', Rs, maxIterations, maxEps)
}

fisherAxisC <- function(Qs, Qhat) {
    .Call('rotations_fisherAxisC', PACKAGE = 'rotations', Qs, Qhat)
}

fisherAxisCSymmetric <- function(Qs, Qhat) {
    .Call('rotations_fisherAxisCSymmetric', PACKAGE = 'rotations', Qs, Qhat)
}

fisherBootC <- function(Qs, m, symm) {
    .Call('rotations_fisherBootC', PACKAGE = 'rotations', Qs, m, symm)
}

RdistC <- function(Q1, Q2) {
    .Call('rotations_RdistC', PACKAGE = 'rotations', Q1, Q2)
}

rdistSO3C <- function(Rs, R2) {
    .Call('rotations_rdistSO3C', PACKAGE = 'rotations', Rs, R2)
}

EdistC <- function(Q1, Q2) {
    .Call('rotations_EdistC', PACKAGE = 'rotations', Q1, Q2)
}

oneRdistC <- function(Q1, Q2) {
    .Call('rotations_oneRdistC', PACKAGE = 'rotations', Q1, Q2)
}

cdfunsC <- function(Qs, Qhat) {
    .Call('rotations_cdfunsC', PACKAGE = 'rotations', Qs, Qhat)
}

cdfunsCMedian <- function(Qs, Qhat) {
    .Call('rotations_cdfunsCMedian', PACKAGE = 'rotations', Qs, Qhat)
}

zhangQ4 <- function(Q, m) {
    .Call('rotations_zhangQ4', PACKAGE = 'rotations', Q, m)
}

cdfunsCSO3 <- function(Rs, Rhat) {
    .Call('rotations_cdfunsCSO3', PACKAGE = 'rotations', Rs, Rhat)
}

zhangMedianC <- function(Rs, m) {
    .Call('rotations_zhangMedianC', PACKAGE = 'rotations', Rs, m)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('rotations_RcppExport_registerCCallable', PACKAGE = 'rotations')
})
