# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Check that each row of Q is a quaternion, i.e., length 1
checkQ4 <- function(Q) {
    .Call('rotations2_checkQ4', PACKAGE = 'rotations2', Q)
}

#' Check that each row of Rs is a rotation matrix, i.e. R'R=I and det(R)=1
checkSO3 <- function(Rs) {
    .Call('rotations2_checkSO3', PACKAGE = 'rotations2', Rs)
}

#' Exponentiate a skew-symmetric matrix, which is necessairly a rotation
expskewC <- function(M) {
    .Call('rotations2_expskewC', PACKAGE = 'rotations2', M)
}

#' Compue the geodesic distance between each row of Rs and R2
rdistSO3C <- function(Rs, R2) {
    .Call('rotations2_rdistSO3C', PACKAGE = 'rotations2', Rs, R2)
}

#' Compute the natural log of a rotation matrix, which is skew-symmetric
logSO3C <- function(R) {
    .Call('rotations2_logSO3C', PACKAGE = 'rotations2', R)
}

#' Project 3-by-3 skew symmetric matrix into SO3
projectSO3C <- function(M) {
    .Call('rotations2_projectSO3C', PACKAGE = 'rotations2', M)
}

#' Projected mean for SO3
meanSO3C <- function(Rs) {
    .Call('rotations2_meanSO3C', PACKAGE = 'rotations2', Rs)
}

#' Compute projected mean for quaternions
meanQ4C <- function(Q) {
    .Call('rotations2_meanQ4C', PACKAGE = 'rotations2', Q)
}

#' Compute projected Median in SO3
medianSO3C <- function(Rs) {
    .Call('rotations2_medianSO3C', PACKAGE = 'rotations2', Rs)
}

#' Compute intrinsic median in SO3 
HartmedianSO3C <- function(Rs) {
    .Call('rotations2_HartmedianSO3C', PACKAGE = 'rotations2', Rs)
}

#' Compute geometric mean in SO3
gmeanSO3C <- function(Rs) {
    .Call('rotations2_gmeanSO3C', PACKAGE = 'rotations2', Rs)
}

fisherAxisC <- function(Qs, Qhat) {
    .Call('rotations2_fisherAxisC', PACKAGE = 'rotations2', Qs, Qhat)
}

fisherBootC <- function(Qs, m) {
    .Call('rotations2_fisherBootC', PACKAGE = 'rotations2', Qs, m)
}

RdistC <- function(Q1, Q2) {
    .Call('rotations2_RdistC', PACKAGE = 'rotations2', Q1, Q2)
}

cdfunsC <- function(Qs, Qhat) {
    .Call('rotations2_cdfunsC', PACKAGE = 'rotations2', Qs, Qhat)
}

bootQhat <- function(Q, m) {
    .Call('rotations2_bootQhat', PACKAGE = 'rotations2', Q, m)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('rotations2_RcppExport_registerCCallable', PACKAGE = 'rotations2')
})
