# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eskewC <- function(U) {
    .Call('rotations2_eskewC', PACKAGE = 'rotations2', U)
}

SO3defaultC <- function(U, theta) {
    .Call('rotations2_SO3defaultC', PACKAGE = 'rotations2', U, theta)
}

Q4defaultC <- function(U, theta) {
    .Call('rotations2_Q4defaultC', PACKAGE = 'rotations2', U, theta)
}

pMatC <- function(p) {
    .Call('rotations2_pMatC', PACKAGE = 'rotations2', p)
}

genrC <- function(r, S, SO3, u) {
    .Call('rotations2_genrC', PACKAGE = 'rotations2', r, S, SO3, u)
}

checkQ4 <- function(Q) {
    .Call('rotations2_checkQ4', PACKAGE = 'rotations2', Q)
}

checkSO3 <- function(Rs) {
    .Call('rotations2_checkSO3', PACKAGE = 'rotations2', Rs)
}

expskewC <- function(M) {
    .Call('rotations2_expskewC', PACKAGE = 'rotations2', M)
}

rdistSO3C <- function(Rs, R2) {
    .Call('rotations2_rdistSO3C', PACKAGE = 'rotations2', Rs, R2)
}

logSO3C <- function(R) {
    .Call('rotations2_logSO3C', PACKAGE = 'rotations2', R)
}

projectSO3C <- function(M) {
    .Call('rotations2_projectSO3C', PACKAGE = 'rotations2', M)
}

meanSO3C <- function(Rs) {
    .Call('rotations2_meanSO3C', PACKAGE = 'rotations2', Rs)
}

meanQ4C <- function(Q) {
    .Call('rotations2_meanQ4C', PACKAGE = 'rotations2', Q)
}

medianSO3C <- function(Rs, maxIterations, maxEps) {
    .Call('rotations2_medianSO3C', PACKAGE = 'rotations2', Rs, maxIterations, maxEps)
}

HartmedianSO3C <- function(Rs, maxIterations, maxEps) {
    .Call('rotations2_HartmedianSO3C', PACKAGE = 'rotations2', Rs, maxIterations, maxEps)
}

gmeanSO3C <- function(Rs, maxIterations, maxEps) {
    .Call('rotations2_gmeanSO3C', PACKAGE = 'rotations2', Rs, maxIterations, maxEps)
}

fisherAxisC <- function(Qs, Qhat) {
    .Call('rotations2_fisherAxisC', PACKAGE = 'rotations2', Qs, Qhat)
}

fisherAxisCSymmetric <- function(Qs, Qhat) {
    .Call('rotations2_fisherAxisCSymmetric', PACKAGE = 'rotations2', Qs, Qhat)
}

fisherBootC <- function(Qs, m, symm) {
    .Call('rotations2_fisherBootC', PACKAGE = 'rotations2', Qs, m, symm)
}

RdistC <- function(Q1, Q2) {
    .Call('rotations2_RdistC', PACKAGE = 'rotations2', Q1, Q2)
}

EdistC <- function(Q1, Q2) {
    .Call('rotations2_EdistC', PACKAGE = 'rotations2', Q1, Q2)
}

oneRdistC <- function(Q1, Q2) {
    .Call('rotations2_oneRdistC', PACKAGE = 'rotations2', Q1, Q2)
}

cdfunsC <- function(Qs, Qhat) {
    .Call('rotations2_cdfunsC', PACKAGE = 'rotations2', Qs, Qhat)
}

zhangQ4 <- function(Q, m) {
    .Call('rotations2_zhangQ4', PACKAGE = 'rotations2', Q, m)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('rotations2_RcppExport_registerCCallable', PACKAGE = 'rotations2')
})
