// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/rotations.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// eskewC
arma::mat eskewC(arma::rowvec U);
static SEXP rotations_eskewC_try(SEXP USEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::rowvec >::type U(USEXP);
    __result = Rcpp::wrap(eskewC(U));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_eskewC(SEXP USEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_eskewC_try(USEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// SO3defaultC
arma::mat SO3defaultC(arma::mat U, arma::vec theta);
static SEXP rotations_SO3defaultC_try(SEXP USEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    __result = Rcpp::wrap(SO3defaultC(U, theta));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_SO3defaultC(SEXP USEXP, SEXP thetaSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_SO3defaultC_try(USEXP, thetaSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// Q4defaultC
arma::mat Q4defaultC(arma::mat U, arma::vec theta);
static SEXP rotations_Q4defaultC_try(SEXP USEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    __result = Rcpp::wrap(Q4defaultC(U, theta));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_Q4defaultC(SEXP USEXP, SEXP thetaSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_Q4defaultC_try(USEXP, thetaSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// pMatC
arma::mat pMatC(arma::mat p);
static SEXP rotations_pMatC_try(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type p(pSEXP);
    __result = Rcpp::wrap(pMatC(p));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_pMatC(SEXP pSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_pMatC_try(pSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// genrC
arma::mat genrC(arma::vec r, arma::mat S, int SO3, arma::mat u);
static SEXP rotations_genrC_try(SEXP rSEXP, SEXP SSEXP, SEXP SO3SEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::vec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type SO3(SO3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type u(uSEXP);
    __result = Rcpp::wrap(genrC(r, S, SO3, u));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_genrC(SEXP rSEXP, SEXP SSEXP, SEXP SO3SEXP, SEXP uSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_genrC_try(rSEXP, SSEXP, SO3SEXP, uSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// rcayleyCpp
NumericVector rcayleyCpp(int n, double kappa);
static SEXP rotations_rcayleyCpp_try(SEXP nSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    __result = Rcpp::wrap(rcayleyCpp(n, kappa));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_rcayleyCpp(SEXP nSEXP, SEXP kappaSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_rcayleyCpp_try(nSEXP, kappaSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// rmbCpp
NumericVector rmbCpp(int n, double kappa);
static SEXP rotations_rmbCpp_try(SEXP nSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    __result = Rcpp::wrap(rmbCpp(n, kappa));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_rmbCpp(SEXP nSEXP, SEXP kappaSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_rmbCpp_try(nSEXP, kappaSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// rfisherCpp
NumericVector rfisherCpp(int n, double kappa);
static SEXP rotations_rfisherCpp_try(SEXP nSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    __result = Rcpp::wrap(rfisherCpp(n, kappa));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_rfisherCpp(SEXP nSEXP, SEXP kappaSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_rfisherCpp_try(nSEXP, kappaSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// rvmisesCPP
NumericVector rvmisesCPP(int n, double kappa);
static SEXP rotations_rvmisesCPP_try(SEXP nSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    __result = Rcpp::wrap(rvmisesCPP(n, kappa));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_rvmisesCPP(SEXP nSEXP, SEXP kappaSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_rvmisesCPP_try(nSEXP, kappaSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// centerCpp
arma::mat centerCpp(arma::mat Rs, arma::mat S);
static SEXP rotations_centerCpp_try(SEXP RsSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    __result = Rcpp::wrap(centerCpp(Rs, S));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_centerCpp(SEXP RsSEXP, SEXP SSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_centerCpp_try(RsSEXP, SSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// lpvmises
double lpvmises(arma::mat Rs, arma::mat S, double kappa);
static SEXP rotations_lpvmises_try(SEXP RsSEXP, SEXP SSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    __result = Rcpp::wrap(lpvmises(Rs, S, kappa));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_lpvmises(SEXP RsSEXP, SEXP SSEXP, SEXP kappaSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_lpvmises_try(RsSEXP, SSEXP, kappaSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// lpfisher
double lpfisher(arma::mat Rs, arma::mat S, double kappa);
static SEXP rotations_lpfisher_try(SEXP RsSEXP, SEXP SSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    __result = Rcpp::wrap(lpfisher(Rs, S, kappa));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_lpfisher(SEXP RsSEXP, SEXP SSEXP, SEXP kappaSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_lpfisher_try(RsSEXP, SSEXP, kappaSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// lpcayley
double lpcayley(arma::mat Rs, arma::mat S, double kappa);
static SEXP rotations_lpcayley_try(SEXP RsSEXP, SEXP SSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    __result = Rcpp::wrap(lpcayley(Rs, S, kappa));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_lpcayley(SEXP RsSEXP, SEXP SSEXP, SEXP kappaSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_lpcayley_try(RsSEXP, SSEXP, kappaSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// S_MCMC_CPP
arma::mat S_MCMC_CPP(arma::mat Rs, arma::mat oldS, double rho, double kappa, int Dist);
static SEXP rotations_S_MCMC_CPP_try(SEXP RsSEXP, SEXP oldSSEXP, SEXP rhoSEXP, SEXP kappaSEXP, SEXP DistSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type oldS(oldSSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< int >::type Dist(DistSEXP);
    __result = Rcpp::wrap(S_MCMC_CPP(Rs, oldS, rho, kappa, Dist));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_S_MCMC_CPP(SEXP RsSEXP, SEXP oldSSEXP, SEXP rhoSEXP, SEXP kappaSEXP, SEXP DistSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_S_MCMC_CPP_try(RsSEXP, oldSSEXP, rhoSEXP, kappaSEXP, DistSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// kap_MCMC_CPP
double kap_MCMC_CPP(arma::mat Rs, double oldKappa, double sigma, arma::mat S, int Dist);
static SEXP rotations_kap_MCMC_CPP_try(SEXP RsSEXP, SEXP oldKappaSEXP, SEXP sigmaSEXP, SEXP SSEXP, SEXP DistSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< double >::type oldKappa(oldKappaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type Dist(DistSEXP);
    __result = Rcpp::wrap(kap_MCMC_CPP(Rs, oldKappa, sigma, S, Dist));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_kap_MCMC_CPP(SEXP RsSEXP, SEXP oldKappaSEXP, SEXP sigmaSEXP, SEXP SSEXP, SEXP DistSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_kap_MCMC_CPP_try(RsSEXP, oldKappaSEXP, sigmaSEXP, SSEXP, DistSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// afun_CPP
arma::rowvec afun_CPP(arma::mat R1, arma::mat R2);
static SEXP rotations_afun_CPP_try(SEXP R1SEXP, SEXP R2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type R1(R1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R2(R2SEXP);
    __result = Rcpp::wrap(afun_CPP(R1, R2));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_afun_CPP(SEXP R1SEXP, SEXP R2SEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_afun_CPP_try(R1SEXP, R2SEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// both_MCMC_CPP
List both_MCMC_CPP(arma::mat Rs, arma::mat S0, double kappa0, double rho, double sigma, int burnin, int B, int Dist);
static SEXP rotations_both_MCMC_CPP_try(SEXP RsSEXP, SEXP S0SEXP, SEXP kappa0SEXP, SEXP rhoSEXP, SEXP sigmaSEXP, SEXP burninSEXP, SEXP BSEXP, SEXP DistSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< double >::type kappa0(kappa0SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type Dist(DistSEXP);
    __result = Rcpp::wrap(both_MCMC_CPP(Rs, S0, kappa0, rho, sigma, burnin, B, Dist));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_both_MCMC_CPP(SEXP RsSEXP, SEXP S0SEXP, SEXP kappa0SEXP, SEXP rhoSEXP, SEXP sigmaSEXP, SEXP burninSEXP, SEXP BSEXP, SEXP DistSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_both_MCMC_CPP_try(RsSEXP, S0SEXP, kappa0SEXP, rhoSEXP, sigmaSEXP, burninSEXP, BSEXP, DistSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// checkQ4
int checkQ4(NumericMatrix Q);
static SEXP rotations_checkQ4_try(SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericMatrix >::type Q(QSEXP);
    __result = Rcpp::wrap(checkQ4(Q));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_checkQ4(SEXP QSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_checkQ4_try(QSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// checkSO3
int checkSO3(arma::mat Rs);
static SEXP rotations_checkSO3_try(SEXP RsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    __result = Rcpp::wrap(checkSO3(Rs));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_checkSO3(SEXP RsSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_checkSO3_try(RsSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// expskewC
arma::mat expskewC(arma::mat M);
static SEXP rotations_expskewC_try(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    __result = Rcpp::wrap(expskewC(M));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_expskewC(SEXP MSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_expskewC_try(MSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// expskewCMulti
arma::mat expskewCMulti(arma::mat M);
static SEXP rotations_expskewCMulti_try(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    __result = Rcpp::wrap(expskewCMulti(M));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_expskewCMulti(SEXP MSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_expskewCMulti_try(MSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// logSO3C
arma::mat logSO3C(arma::mat R);
static SEXP rotations_logSO3C_try(SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    __result = Rcpp::wrap(logSO3C(R));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_logSO3C(SEXP RSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_logSO3C_try(RSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// logSO3CMulti
arma::mat logSO3CMulti(arma::mat R);
static SEXP rotations_logSO3CMulti_try(SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    __result = Rcpp::wrap(logSO3CMulti(R));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_logSO3CMulti(SEXP RSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_logSO3CMulti_try(RSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// projectSO3C
arma::mat projectSO3C(arma::mat M);
static SEXP rotations_projectSO3C_try(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    __result = Rcpp::wrap(projectSO3C(M));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_projectSO3C(SEXP MSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_projectSO3C_try(MSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// meanSO3C
arma::mat meanSO3C(arma::mat Rs);
static SEXP rotations_meanSO3C_try(SEXP RsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    __result = Rcpp::wrap(meanSO3C(Rs));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_meanSO3C(SEXP RsSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_meanSO3C_try(RsSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// meanQ4C
arma::rowvec meanQ4C(arma::mat Q);
static SEXP rotations_meanQ4C_try(SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    __result = Rcpp::wrap(meanQ4C(Q));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_meanQ4C(SEXP QSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_meanQ4C_try(QSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// medianSO3C
arma::mat medianSO3C(arma::mat Rs, int maxIterations, double maxEps);
static SEXP rotations_medianSO3C_try(SEXP RsSEXP, SEXP maxIterationsSEXP, SEXP maxEpsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< int >::type maxIterations(maxIterationsSEXP);
    Rcpp::traits::input_parameter< double >::type maxEps(maxEpsSEXP);
    __result = Rcpp::wrap(medianSO3C(Rs, maxIterations, maxEps));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_medianSO3C(SEXP RsSEXP, SEXP maxIterationsSEXP, SEXP maxEpsSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_medianSO3C_try(RsSEXP, maxIterationsSEXP, maxEpsSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// HartmedianSO3C
arma::mat HartmedianSO3C(arma::mat Rs, int maxIterations, double maxEps);
static SEXP rotations_HartmedianSO3C_try(SEXP RsSEXP, SEXP maxIterationsSEXP, SEXP maxEpsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< int >::type maxIterations(maxIterationsSEXP);
    Rcpp::traits::input_parameter< double >::type maxEps(maxEpsSEXP);
    __result = Rcpp::wrap(HartmedianSO3C(Rs, maxIterations, maxEps));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_HartmedianSO3C(SEXP RsSEXP, SEXP maxIterationsSEXP, SEXP maxEpsSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_HartmedianSO3C_try(RsSEXP, maxIterationsSEXP, maxEpsSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// gmeanSO3C
arma::mat gmeanSO3C(arma::mat Rs, int maxIterations, double maxEps);
static SEXP rotations_gmeanSO3C_try(SEXP RsSEXP, SEXP maxIterationsSEXP, SEXP maxEpsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< int >::type maxIterations(maxIterationsSEXP);
    Rcpp::traits::input_parameter< double >::type maxEps(maxEpsSEXP);
    __result = Rcpp::wrap(gmeanSO3C(Rs, maxIterations, maxEps));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_gmeanSO3C(SEXP RsSEXP, SEXP maxIterationsSEXP, SEXP maxEpsSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_gmeanSO3C_try(RsSEXP, maxIterationsSEXP, maxEpsSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// fisherAxisC
double fisherAxisC(arma::mat Qs, arma::rowvec Qhat);
static SEXP rotations_fisherAxisC_try(SEXP QsSEXP, SEXP QhatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Qs(QsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type Qhat(QhatSEXP);
    __result = Rcpp::wrap(fisherAxisC(Qs, Qhat));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_fisherAxisC(SEXP QsSEXP, SEXP QhatSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_fisherAxisC_try(QsSEXP, QhatSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// fisherAxisCSymmetric
double fisherAxisCSymmetric(arma::mat Qs, arma::rowvec Qhat);
static SEXP rotations_fisherAxisCSymmetric_try(SEXP QsSEXP, SEXP QhatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Qs(QsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type Qhat(QhatSEXP);
    __result = Rcpp::wrap(fisherAxisCSymmetric(Qs, Qhat));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_fisherAxisCSymmetric(SEXP QsSEXP, SEXP QhatSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_fisherAxisCSymmetric_try(QsSEXP, QhatSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// fisherBootC
arma::vec fisherBootC(arma::mat Qs, int m, bool symm);
static SEXP rotations_fisherBootC_try(SEXP QsSEXP, SEXP mSEXP, SEXP symmSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Qs(QsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< bool >::type symm(symmSEXP);
    __result = Rcpp::wrap(fisherBootC(Qs, m, symm));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_fisherBootC(SEXP QsSEXP, SEXP mSEXP, SEXP symmSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_fisherBootC_try(QsSEXP, mSEXP, symmSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// HnCpp
arma::rowvec HnCpp(arma::mat Qs);
static SEXP rotations_HnCpp_try(SEXP QsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Qs(QsSEXP);
    __result = Rcpp::wrap(HnCpp(Qs));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_HnCpp(SEXP QsSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_HnCpp_try(QsSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// HnCppIntrinsic
arma::rowvec HnCppIntrinsic(arma::mat Qs);
static SEXP rotations_HnCppIntrinsic_try(SEXP QsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Qs(QsSEXP);
    __result = Rcpp::wrap(HnCppIntrinsic(Qs));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_HnCppIntrinsic(SEXP QsSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_HnCppIntrinsic_try(QsSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// HnCppBloc
arma::rowvec HnCppBloc(arma::mat Qs, arma::mat Cs);
static SEXP rotations_HnCppBloc_try(SEXP QsSEXP, SEXP CsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Qs(QsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Cs(CsSEXP);
    __result = Rcpp::wrap(HnCppBloc(Qs, Cs));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_HnCppBloc(SEXP QsSEXP, SEXP CsSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_HnCppBloc_try(QsSEXP, CsSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// RdistC
NumericVector RdistC(NumericMatrix Q1, NumericVector Q2);
static SEXP rotations_RdistC_try(SEXP Q1SEXP, SEXP Q2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericMatrix >::type Q1(Q1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Q2(Q2SEXP);
    __result = Rcpp::wrap(RdistC(Q1, Q2));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_RdistC(SEXP Q1SEXP, SEXP Q2SEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_RdistC_try(Q1SEXP, Q2SEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// rdistSO3C
arma::rowvec rdistSO3C(arma::mat Rs, arma::mat R2);
static SEXP rotations_rdistSO3C_try(SEXP RsSEXP, SEXP R2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R2(R2SEXP);
    __result = Rcpp::wrap(rdistSO3C(Rs, R2));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_rdistSO3C(SEXP RsSEXP, SEXP R2SEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_rdistSO3C_try(RsSEXP, R2SEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// EdistC
NumericVector EdistC(NumericMatrix Q1, NumericVector Q2);
static SEXP rotations_EdistC_try(SEXP Q1SEXP, SEXP Q2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericMatrix >::type Q1(Q1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Q2(Q2SEXP);
    __result = Rcpp::wrap(EdistC(Q1, Q2));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_EdistC(SEXP Q1SEXP, SEXP Q2SEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_EdistC_try(Q1SEXP, Q2SEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// oneRdistC
double oneRdistC(NumericMatrix Q1, NumericVector Q2);
static SEXP rotations_oneRdistC_try(SEXP Q1SEXP, SEXP Q2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericMatrix >::type Q1(Q1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Q2(Q2SEXP);
    __result = Rcpp::wrap(oneRdistC(Q1, Q2));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_oneRdistC(SEXP Q1SEXP, SEXP Q2SEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_oneRdistC_try(Q1SEXP, Q2SEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// cdfunsC
NumericVector cdfunsC(NumericMatrix Qs, NumericVector Qhat);
static SEXP rotations_cdfunsC_try(SEXP QsSEXP, SEXP QhatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericMatrix >::type Qs(QsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Qhat(QhatSEXP);
    __result = Rcpp::wrap(cdfunsC(Qs, Qhat));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_cdfunsC(SEXP QsSEXP, SEXP QhatSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_cdfunsC_try(QsSEXP, QhatSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// cdfunsCMedian
NumericVector cdfunsCMedian(NumericMatrix Qs, NumericVector Qhat);
static SEXP rotations_cdfunsCMedian_try(SEXP QsSEXP, SEXP QhatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericMatrix >::type Qs(QsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Qhat(QhatSEXP);
    __result = Rcpp::wrap(cdfunsCMedian(Qs, Qhat));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_cdfunsCMedian(SEXP QsSEXP, SEXP QhatSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_cdfunsCMedian_try(QsSEXP, QhatSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// zhangQ4
NumericVector zhangQ4(NumericMatrix Q, int m);
static SEXP rotations_zhangQ4_try(SEXP QSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericMatrix >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    __result = Rcpp::wrap(zhangQ4(Q, m));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_zhangQ4(SEXP QSEXP, SEXP mSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_zhangQ4_try(QSEXP, mSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// cdfunsCSO3
NumericVector cdfunsCSO3(arma::mat Rs, arma::mat Rhat);
static SEXP rotations_cdfunsCSO3_try(SEXP RsSEXP, SEXP RhatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Rhat(RhatSEXP);
    __result = Rcpp::wrap(cdfunsCSO3(Rs, Rhat));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_cdfunsCSO3(SEXP RsSEXP, SEXP RhatSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_cdfunsCSO3_try(RsSEXP, RhatSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// zhangMedianC
NumericVector zhangMedianC(arma::mat Rs, int m);
static SEXP rotations_zhangMedianC_try(SEXP RsSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::mat >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    __result = Rcpp::wrap(zhangMedianC(Rs, m));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP rotations_zhangMedianC(SEXP RsSEXP, SEXP mSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(rotations_zhangMedianC_try(RsSEXP, mSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}

// validate (ensure exported C++ functions exist before calling them)
static int rotations_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("arma::mat(*eskewC)(arma::rowvec)");
        signatures.insert("arma::mat(*SO3defaultC)(arma::mat,arma::vec)");
        signatures.insert("arma::mat(*Q4defaultC)(arma::mat,arma::vec)");
        signatures.insert("arma::mat(*pMatC)(arma::mat)");
        signatures.insert("arma::mat(*genrC)(arma::vec,arma::mat,int,arma::mat)");
        signatures.insert("NumericVector(*rcayleyCpp)(int,double)");
        signatures.insert("NumericVector(*rmbCpp)(int,double)");
        signatures.insert("NumericVector(*rfisherCpp)(int,double)");
        signatures.insert("NumericVector(*rvmisesCPP)(int,double)");
        signatures.insert("arma::mat(*centerCpp)(arma::mat,arma::mat)");
        signatures.insert("double(*lpvmises)(arma::mat,arma::mat,double)");
        signatures.insert("double(*lpfisher)(arma::mat,arma::mat,double)");
        signatures.insert("double(*lpcayley)(arma::mat,arma::mat,double)");
        signatures.insert("arma::mat(*S_MCMC_CPP)(arma::mat,arma::mat,double,double,int)");
        signatures.insert("double(*kap_MCMC_CPP)(arma::mat,double,double,arma::mat,int)");
        signatures.insert("arma::rowvec(*afun_CPP)(arma::mat,arma::mat)");
        signatures.insert("List(*both_MCMC_CPP)(arma::mat,arma::mat,double,double,double,int,int,int)");
        signatures.insert("int(*checkQ4)(NumericMatrix)");
        signatures.insert("int(*checkSO3)(arma::mat)");
        signatures.insert("arma::mat(*expskewC)(arma::mat)");
        signatures.insert("arma::mat(*expskewCMulti)(arma::mat)");
        signatures.insert("arma::mat(*logSO3C)(arma::mat)");
        signatures.insert("arma::mat(*logSO3CMulti)(arma::mat)");
        signatures.insert("arma::mat(*projectSO3C)(arma::mat)");
        signatures.insert("arma::mat(*meanSO3C)(arma::mat)");
        signatures.insert("arma::rowvec(*meanQ4C)(arma::mat)");
        signatures.insert("arma::mat(*medianSO3C)(arma::mat,int,double)");
        signatures.insert("arma::mat(*HartmedianSO3C)(arma::mat,int,double)");
        signatures.insert("arma::mat(*gmeanSO3C)(arma::mat,int,double)");
        signatures.insert("double(*fisherAxisC)(arma::mat,arma::rowvec)");
        signatures.insert("double(*fisherAxisCSymmetric)(arma::mat,arma::rowvec)");
        signatures.insert("arma::vec(*fisherBootC)(arma::mat,int,bool)");
        signatures.insert("arma::rowvec(*HnCpp)(arma::mat)");
        signatures.insert("arma::rowvec(*HnCppIntrinsic)(arma::mat)");
        signatures.insert("arma::rowvec(*HnCppBloc)(arma::mat,arma::mat)");
        signatures.insert("NumericVector(*RdistC)(NumericMatrix,NumericVector)");
        signatures.insert("arma::rowvec(*rdistSO3C)(arma::mat,arma::mat)");
        signatures.insert("NumericVector(*EdistC)(NumericMatrix,NumericVector)");
        signatures.insert("double(*oneRdistC)(NumericMatrix,NumericVector)");
        signatures.insert("NumericVector(*cdfunsC)(NumericMatrix,NumericVector)");
        signatures.insert("NumericVector(*cdfunsCMedian)(NumericMatrix,NumericVector)");
        signatures.insert("NumericVector(*zhangQ4)(NumericMatrix,int)");
        signatures.insert("NumericVector(*cdfunsCSO3)(arma::mat,arma::mat)");
        signatures.insert("NumericVector(*zhangMedianC)(arma::mat,int)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP rotations_RcppExport_registerCCallable() { 
    R_RegisterCCallable("rotations", "rotations_eskewC", (DL_FUNC)rotations_eskewC_try);
    R_RegisterCCallable("rotations", "rotations_SO3defaultC", (DL_FUNC)rotations_SO3defaultC_try);
    R_RegisterCCallable("rotations", "rotations_Q4defaultC", (DL_FUNC)rotations_Q4defaultC_try);
    R_RegisterCCallable("rotations", "rotations_pMatC", (DL_FUNC)rotations_pMatC_try);
    R_RegisterCCallable("rotations", "rotations_genrC", (DL_FUNC)rotations_genrC_try);
    R_RegisterCCallable("rotations", "rotations_rcayleyCpp", (DL_FUNC)rotations_rcayleyCpp_try);
    R_RegisterCCallable("rotations", "rotations_rmbCpp", (DL_FUNC)rotations_rmbCpp_try);
    R_RegisterCCallable("rotations", "rotations_rfisherCpp", (DL_FUNC)rotations_rfisherCpp_try);
    R_RegisterCCallable("rotations", "rotations_rvmisesCPP", (DL_FUNC)rotations_rvmisesCPP_try);
    R_RegisterCCallable("rotations", "rotations_centerCpp", (DL_FUNC)rotations_centerCpp_try);
    R_RegisterCCallable("rotations", "rotations_lpvmises", (DL_FUNC)rotations_lpvmises_try);
    R_RegisterCCallable("rotations", "rotations_lpfisher", (DL_FUNC)rotations_lpfisher_try);
    R_RegisterCCallable("rotations", "rotations_lpcayley", (DL_FUNC)rotations_lpcayley_try);
    R_RegisterCCallable("rotations", "rotations_S_MCMC_CPP", (DL_FUNC)rotations_S_MCMC_CPP_try);
    R_RegisterCCallable("rotations", "rotations_kap_MCMC_CPP", (DL_FUNC)rotations_kap_MCMC_CPP_try);
    R_RegisterCCallable("rotations", "rotations_afun_CPP", (DL_FUNC)rotations_afun_CPP_try);
    R_RegisterCCallable("rotations", "rotations_both_MCMC_CPP", (DL_FUNC)rotations_both_MCMC_CPP_try);
    R_RegisterCCallable("rotations", "rotations_checkQ4", (DL_FUNC)rotations_checkQ4_try);
    R_RegisterCCallable("rotations", "rotations_checkSO3", (DL_FUNC)rotations_checkSO3_try);
    R_RegisterCCallable("rotations", "rotations_expskewC", (DL_FUNC)rotations_expskewC_try);
    R_RegisterCCallable("rotations", "rotations_expskewCMulti", (DL_FUNC)rotations_expskewCMulti_try);
    R_RegisterCCallable("rotations", "rotations_logSO3C", (DL_FUNC)rotations_logSO3C_try);
    R_RegisterCCallable("rotations", "rotations_logSO3CMulti", (DL_FUNC)rotations_logSO3CMulti_try);
    R_RegisterCCallable("rotations", "rotations_projectSO3C", (DL_FUNC)rotations_projectSO3C_try);
    R_RegisterCCallable("rotations", "rotations_meanSO3C", (DL_FUNC)rotations_meanSO3C_try);
    R_RegisterCCallable("rotations", "rotations_meanQ4C", (DL_FUNC)rotations_meanQ4C_try);
    R_RegisterCCallable("rotations", "rotations_medianSO3C", (DL_FUNC)rotations_medianSO3C_try);
    R_RegisterCCallable("rotations", "rotations_HartmedianSO3C", (DL_FUNC)rotations_HartmedianSO3C_try);
    R_RegisterCCallable("rotations", "rotations_gmeanSO3C", (DL_FUNC)rotations_gmeanSO3C_try);
    R_RegisterCCallable("rotations", "rotations_fisherAxisC", (DL_FUNC)rotations_fisherAxisC_try);
    R_RegisterCCallable("rotations", "rotations_fisherAxisCSymmetric", (DL_FUNC)rotations_fisherAxisCSymmetric_try);
    R_RegisterCCallable("rotations", "rotations_fisherBootC", (DL_FUNC)rotations_fisherBootC_try);
    R_RegisterCCallable("rotations", "rotations_HnCpp", (DL_FUNC)rotations_HnCpp_try);
    R_RegisterCCallable("rotations", "rotations_HnCppIntrinsic", (DL_FUNC)rotations_HnCppIntrinsic_try);
    R_RegisterCCallable("rotations", "rotations_HnCppBloc", (DL_FUNC)rotations_HnCppBloc_try);
    R_RegisterCCallable("rotations", "rotations_RdistC", (DL_FUNC)rotations_RdistC_try);
    R_RegisterCCallable("rotations", "rotations_rdistSO3C", (DL_FUNC)rotations_rdistSO3C_try);
    R_RegisterCCallable("rotations", "rotations_EdistC", (DL_FUNC)rotations_EdistC_try);
    R_RegisterCCallable("rotations", "rotations_oneRdistC", (DL_FUNC)rotations_oneRdistC_try);
    R_RegisterCCallable("rotations", "rotations_cdfunsC", (DL_FUNC)rotations_cdfunsC_try);
    R_RegisterCCallable("rotations", "rotations_cdfunsCMedian", (DL_FUNC)rotations_cdfunsCMedian_try);
    R_RegisterCCallable("rotations", "rotations_zhangQ4", (DL_FUNC)rotations_zhangQ4_try);
    R_RegisterCCallable("rotations", "rotations_cdfunsCSO3", (DL_FUNC)rotations_cdfunsCSO3_try);
    R_RegisterCCallable("rotations", "rotations_zhangMedianC", (DL_FUNC)rotations_zhangMedianC_try);
    R_RegisterCCallable("rotations", "rotations_RcppExport_validate", (DL_FUNC)rotations_RcppExport_validate);
    return R_NilValue;
}
